[NEW] Added a command to change file extension.

diff --git a/xman_chext b/xman_chext
--- a/xman_chext
+++ b/xman_chext
@@ -21,3 +21,60 @@
 #
 # The GNU General Public License is contained in the file COPYING.
 #
+
+#!/bin/bash
+
+# Author: xman
+# Email : cshinyee@gmail.com
+# Date  : 08 Aug 2006
+
+# Syntax: xman_chext <FILE> <EXT>
+
+# Given: A file.
+# Output: Change the file extension to EXT.
+
+# Known problems/limitations:
+
+newline=$'\n'
+
+#########################################################################################
+
+if [ -z "$2" ] ; then
+	echo "usage: xman_chext <FILE> <EXT>"
+	echo "Change the file extension of FILE to EXT."
+	exit 0
+fi
+
+f="$1"		# Given file
+ext="$2"	# New extension
+
+if [ ! -e "$f" ] ; then
+	echo "Cannot find: $f"
+	exit 1
+fi
+
+d=`dirname "$f"`
+# $d doesnt start with "/"? 
+if [ "${d:0:1}" != "/" ] ; then
+	# $d is a relative path.
+	# Prepend $d with current directory to obtain the absolute path.
+	d="$PWD/$d"
+fi
+
+b=`basename "$f"`
+if [ "$d" == "$b" ] ; then
+	echo "dir name = file name?: $f"
+	exit 1
+fi
+
+dfname="${b%.*}.$ext"	# File name with new extension.
+if [ ! -e "$d/$dfname" ] ; then
+	mv "$f" "$d/$dfname"
+else	
+	echo "$dfname exists. Skip."
+fi
+
+exit 0
+
+#eof
+
